### ISSUE TITLE
Why you make a request to the keycloak server?

### ISSUE THREAD

**Issue by approached** [el-abdel/ABELkeycloakBearerOnlyAdapterBundle#9]
Hi @ all

This package is nice. 

But why you make curl request to the keycloak server?
https://github.com/el-abdel/ABELkeycloakBearerOnlyAdapterBundle/blob/master/Security/User/KeycloakBearerUserProvider.php#L103

You need just verify the token. For example:
https://github.com/firebase/php-jwt#example-with-a-passphrase

**Comment by el-abdel** [comment]
Hello @approached 
Thanks for you comment 😊 

Well according to [Keycloak doc](https://github.com/keycloak/keycloak-documentation/blob/main/authorization_services/topics/service-rpt-token-introspection.adoc#_enforcer_overview) it is possible to use both approach to verify the access token. So since Keycloak provide an endpoint to verify the token I used it.

**Comment by approached** [comment]
Thank you for your comment. I will try to implement my own logic.
